<?php

// Countries the company can operate in (ISO 3166-1 alpha-2 => name, default currency and timezone).
// Picking a country pre-selects its currency (must be in config/currencies.php) and its main
// timezone; any other zone of that country can be chosen.
return [
    'BD' => ['name' => 'Bangladesh', 'currency' => 'BDT', 'timezone' => 'Asia/Dhaka'],
    'IN' => ['name' => 'India', 'currency' => 'INR', 'timezone' => 'Asia/Kolkata'],
    'PK' => ['name' => 'Pakistan', 'currency' => 'PKR', 'timezone' => 'Asia/Karachi'],
    'NP' => ['name' => 'Nepal', 'currency' => 'NPR', 'timezone' => 'Asia/Kathmandu'],
    'LK' => ['name' => 'Sri Lanka', 'currency' => 'LKR', 'timezone' => 'Asia/Colombo'],
    'US' => ['name' => 'United States', 'currency' => 'USD', 'timezone' => 'America/New_York'],
    'GB' => ['name' => 'United Kingdom', 'currency' => 'GBP', 'timezone' => 'Europe/London'],
    'IE' => ['name' => 'Ireland', 'currency' => 'EUR', 'timezone' => 'Europe/Dublin'],
    'DE' => ['name' => 'Germany', 'currency' => 'EUR', 'timezone' => 'Europe/Berlin'],
    'FR' => ['name' => 'France', 'currency' => 'EUR', 'timezone' => 'Europe/Paris'],
    'IT' => ['name' => 'Italy', 'currency' => 'EUR', 'timezone' => 'Europe/Rome'],
    'ES' => ['name' => 'Spain', 'currency' => 'EUR', 'timezone' => 'Europe/Madrid'],
    'NL' => ['name' => 'Netherlands', 'currency' => 'EUR', 'timezone' => 'Europe/Amsterdam'],
    'CA' => ['name' => 'Canada', 'currency' => 'CAD', 'timezone' => 'America/Toronto'],
    'AU' => ['name' => 'Australia', 'currency' => 'AUD', 'timezone' => 'Australia/Sydney'],
    'AE' => ['name' => 'United Arab Emirates', 'currency' => 'AED', 'timezone' => 'Asia/Dubai'],
    'SA' => ['name' => 'Saudi Arabia', 'currency' => 'SAR', 'timezone' => 'Asia/Riyadh'],
    'QA' => ['name' => 'Qatar', 'currency' => 'QAR', 'timezone' => 'Asia/Qatar'],
    'MY' => ['name' => 'Malaysia', 'currency' => 'MYR', 'timezone' => 'Asia/Kuala_Lumpur'],
    'SG' => ['name' => 'Singapore', 'currency' => 'SGD', 'timezone' => 'Asia/Singapore'],
    'PH' => ['name' => 'Philippines', 'currency' => 'PHP', 'timezone' => 'Asia/Manila'],
    'TH' => ['name' => 'Thailand', 'currency' => 'THB', 'timezone' => 'Asia/Bangkok'],
    'NG' => ['name' => 'Nigeria', 'currency' => 'NGN', 'timezone' => 'Africa/Lagos'],
    'KE' => ['name' => 'Kenya', 'currency' => 'KES', 'timezone' => 'Africa/Nairobi'],
    'GH' => ['name' => 'Ghana', 'currency' => 'GHS', 'timezone' => 'Africa/Accra'],
    'ZA' => ['name' => 'South Africa', 'currency' => 'ZAR', 'timezone' => 'Africa/Johannesburg'],
    'EG' => ['name' => 'Egypt', 'currency' => 'EGP', 'timezone' => 'Africa/Cairo'],
    'TR' => ['name' => 'Turkey', 'currency' => 'TRY', 'timezone' => 'Europe/Istanbul'],
    'BR' => ['name' => 'Brazil', 'currency' => 'BRL', 'timezone' => 'America/Sao_Paulo'],
    'MX' => ['name' => 'Mexico', 'currency' => 'MXN', 'timezone' => 'America/Mexico_City'],
    'JP' => ['name' => 'Japan', 'currency' => 'JPY', 'timezone' => 'Asia/Tokyo'],
    'KR' => ['name' => 'South Korea', 'currency' => 'KRW', 'timezone' => 'Asia/Seoul'],
    'VN' => ['name' => 'Vietnam', 'currency' => 'VND', 'timezone' => 'Asia/Ho_Chi_Minh'],
    'ID' => ['name' => 'Indonesia', 'currency' => 'IDR', 'timezone' => 'Asia/Jakarta'],
    'KW' => ['name' => 'Kuwait', 'currency' => 'KWD', 'timezone' => 'Asia/Kuwait'],
    'BH' => ['name' => 'Bahrain', 'currency' => 'BHD', 'timezone' => 'Asia/Bahrain'],
    'OM' => ['name' => 'Oman', 'currency' => 'OMR', 'timezone' => 'Asia/Muscat'],
    'JO' => ['name' => 'Jordan', 'currency' => 'JOD', 'timezone' => 'Asia/Amman'],
];
