export const accessGroups = [
    {
        key: 'isp',
        label: 'ISP Panel',
        items: [
            { value: 'zone', label: 'Zone' },
            { value: 'area', label: 'Area' },
            { value: 'areaRestore', label: 'Deleted Area Record (Restore)' },
            { value: 'box', label: 'Box' },
            { value: 'package', label: 'Packages' },
            { value: 'router', label: 'Routers (MikroTik) & live sessions' },
            { value: 'networkBlock', label: 'Site / IP Block (push to routers)' },
            { value: 'connection', label: 'Connections (view / create / edit)' },
            { value: 'connectionAction', label: 'Connection Activate / Suspend / Terminate / Change Package' },
            { value: 'connectionSecret', label: 'View PPPoE Password' },
            { value: 'connectionCredit', label: 'Start Connection on Due (credit, admin only)' },
            { value: 'invoice', label: 'Invoices (view)' },
            { value: 'invoiceCreate', label: 'Manual Invoice / Draft / Issue' },
            { value: 'invoiceGenerate', label: 'Run Invoice Generation' },
            { value: 'invoiceVoid', label: 'Void Invoice' },
            { value: 'billingNote', label: 'Credit / Debit Note' },
            { value: 'ispPayment', label: 'Bill Collection (receive payment)' },
            { value: 'ispPaymentReverse', label: 'Reverse Payment / Move Allocation' },
            { value: 'ispRefund', label: 'Refund' },
            { value: 'onlinePayment', label: 'Online Payments (view)' },
            { value: 'onlinePaymentReview', label: 'Approve / Reject Manual Online Payments' },
            { value: 'paymentGateway', label: 'Payment Gateway Settings (bKash / Nagad / Rocket / SSLCommerz)' },
            { value: 'ispReport', label: 'ISP Reports & Dashboard Figures' },
            { value: 'companyDashboard', label: 'Company Dashboard (branches the user may see)' },
            { value: 'region', label: 'Regions (group branches, regional managers)' },
            { value: 'bandwidth', label: 'Bandwidth Purchase (upstream cost)' },
            { value: 'ispSettings', label: 'ISP Billing Settings' },
            { value: 'ticket', label: 'Support Tickets (view / reply / assign)' },
            { value: 'auditLog', label: 'Audit Log' },
            { value: 'ipPool', label: 'IP Pools (IPAM, IPv6, CGNAT)' },
            { value: 'kycVerify', label: 'Verify / reject KYC documents' },
            { value: 'customerDataRights', label: 'Customer data export & erasure' },
            { value: 'sessionLog', label: 'Session Log search & lawful export' },
            { value: 'queueMonitor', label: 'Background Jobs (router pushes, SMS) and Horizon' },
            { value: 'backup', label: 'Backups: take and download full backups (all customer data)' },
        ],
    },
    {
        key: 'sales',
        label: 'Sales Panel',
        items: [
            { value: 'sale', label: 'Sale Entry' },
            { value: 'saleRecord', label: 'Sale Record' },
            { value: 'saleDelete', label: 'Sale Delete' },
            { value: 'saleRestore', label: 'Deleted Sale Record (Restore)' },
            { value: 'saleReturn', label: 'SaleReturn Entry' },
            { value: 'saleReturnRecord', label: 'SaleReturn Record' },
            { value: 'saleReturnRestore', label: 'Deleted SaleReturn Record (Restore)' },
            { value: 'quotation', label: 'Quotation Entry' },
            { value: 'quotationRecord', label: 'Quotation Record' },
            { value: 'quotationRestore', label: 'Deleted Quotation Record (Restore)' },
        ],
    },
    {
        key: 'purchases',
        label: 'Purchase Panel',
        items: [
            { value: 'purchase', label: 'Purchase Entry' },
            { value: 'purchaseRecord', label: 'Purchase Record' },
            { value: 'purchaseReturn', label: 'PurchaseReturn Entry' },
            { value: 'purchaseReturnRecord', label: 'PurchaseReturn Record' },
            { value: 'damage', label: 'Damage Entry' },
            { value: 'damageRecord', label: 'Damage Record' },
            { value: 'stockAdjustment', label: 'Stock Adjustment Entry' },
            { value: 'stockAdjustmentRecord', label: 'Stock Adjustment Record' },
            { value: 'stockTransfer', label: 'Stock Transfer Entry' },
            { value: 'stockTransferRecord', label: 'Stock Transfer Record' },
        ],
    },
    {
        key: 'careflow',
        label: 'CareFlow Panel',
        items: [
            { value: 'careflowOrder', label: 'CareFlow Order Entry' },
            { value: 'careflowOrderRecord', label: 'CareFlow Order Record' },
            { value: 'careflowOrderEditLocked', label: 'Edit Locked/Completed CareFlow Orders' },
            { value: 'careflowOrderDelete', label: 'Delete CareFlow Orders' },
            { value: 'careflowProvider', label: 'CareFlow Providers' },
            { value: 'careflowSettings', label: 'CareFlow Settings' },
        ],
    },
    {
        key: 'hrm',
        label: 'HRM Panel',
        items: [
            { value: 'salary', label: 'Salary Generate' },
            { value: 'salaryList', label: 'Salary Record' },
            { value: 'salaryApprove', label: 'Salary Approve/Reject' },
            { value: 'advanceSalary', label: 'Advance Salary' },
            { value: 'leave', label: 'Leave Management' },
            { value: 'leaveApprove', label: 'Leave Approve/Reject' },
            { value: 'leaveType', label: 'Leave Type Entry' },
            { value: 'employee', label: 'Employee' },
            { value: 'department', label: 'Department Entry' },
            { value: 'designation', label: 'Designation Entry' },
        ],
    },
    {
        key: 'incentive',
        label: 'Incentive Panel',
        items: [
            { value: 'incentiveSlab', label: 'Incentive Slab Setup' },
            { value: 'incentiveCalculate', label: 'Incentive Calculate/Generate' },
            { value: 'incentiveApprove', label: 'Incentive Approve/Reject/Payout' },
        ],
    },
    {
        key: 'control',
        label: 'Control Panel',
        items: [
            { value: 'product', label: 'Product' },
            { value: 'supplier', label: 'Supplier Entry' },
            { value: 'supplierList', label: 'Supplier List' },
            { value: 'customer', label: 'Customer' },
            { value: 'customerRestore', label: 'Deleted Customer Record (Restore)' },
            { value: 'reseller', label: 'Reseller Entry / Import / Export' },
            { value: 'customerLoginAs', label: 'Login As Customer (portal)' },
            { value: 'resellerLoginAs', label: 'Login As Reseller (portal)' },
            { value: 'resellerRequest', label: 'Reseller Packages, Ledger, Withdrawals & Wallets (view)' },
            { value: 'resellerSettlement', label: 'Pay / Reject Reseller Withdrawals, Record Reseller Deposits' },
            { value: 'unit', label: 'Unit Entry' },
            { value: 'category', label: 'Category Entry' },
            { value: 'subCategory', label: 'Sub Category Entry' },
            { value: 'subCategoryRestore', label: 'Deleted Sub Category Record (Restore)' },
            { value: 'brand', label: 'Brand Entry' },
            { value: 'generic', label: 'Generic Entry' },
            { value: 'company', label: 'Company Entry' },
            { value: 'companyRestore', label: 'Deleted Company Record (Restore)' },
            { value: 'businessInfo', label: 'Business Info' },
        ],
    },
    {
        key: 'userManage',
        label: 'User Manage Panel',
        items: [
            { value: 'user', label: 'User Entry' },
            { value: 'role', label: 'Role Entry' },
            { value: 'userSwitch', label: 'Login As User' },
        ],
    },
    {
        key: 'setting',
        label: 'Setting Panel',
        items: [
            { value: 'companyProfile', label: 'Company Profile' },
            { value: 'smsSetting', label: 'SMS Gateways' },
            { value: 'smsPromotion', label: 'SMS Promotion & SMS Log' },
            { value: 'vatSettings', label: 'VAT Settings' },
            { value: 'pharmacyManage', label: 'Pharmacy Manage' },
            { value: 'quotationSettings', label: 'Quotation Settings' },
            { value: 'sale', label: 'Sale Settings' },
            { value: 'saleReturn', label: 'Sale Return Settings' },
            { value: 'expireManage', label: 'Expire Manage' },
            { value: 'branch', label: 'Branch' },
            { value: 'branchManage', label: 'Branch Manage' },
            { value: 'advanceSetting', label: 'Advance Setting' },
            { value: 'cashCloseSetting', label: 'Cash Close Settings' },
        ],
    },
    {
        key: 'accounts',
        label: 'Accounts Panel',
        items: [
            { value: 'expense', label: 'Expense Entry' },
            { value: 'income', label: 'Income Entry' },
            { value: 'receive', label: 'Receive' },
            { value: 'payment', label: 'Payment' },
            { value: 'paymentRestore', label: 'Deleted Payment Record (Restore)' },
            { value: 'bankTransaction', label: 'BankTransaction' },
            { value: 'bankTransactionRestore', label: 'Deleted Bank Transaction Record (Restore)' },
            { value: 'accounthead', label: 'AccountHead Entry' },
            { value: 'accountheadRestore', label: 'Deleted AccountHead Record (Restore)' },
            { value: 'bank', label: 'Bank Entry' },
            { value: 'bankRestore', label: 'Deleted Bank Record (Restore)' },
            { value: 'investTransaction', label: 'InvestTransaction' },
            { value: 'investTransactionList', label: 'InvestTransaction List' },
            { value: 'invest', label: 'InvestAccount Entry' },
            { value: 'investRestore', label: 'Deleted InvestAccount Record (Restore)' },
            { value: 'asset', label: 'Asset Entry' },
            { value: 'assetRestore', label: 'Deleted Asset Record (Restore)' },
            { value: 'cashClose', label: 'Cash Close' },
        ],
    },
    {
        key: 'subscription',
        label: 'Subscription Panel',
        items: [
            { value: 'license', label: 'License' },
            { value: 'licenseUpdate', label: 'Update' },
            { value: 'licenseBackup', label: 'Backup' },
        ],
    },
    {
        key: 'stockCheck',
        label: 'Stock Check Panel',
        items: [
            { value: 'stockCheckDailyTask', label: 'Daily Task' },
            { value: 'stockCheckRandomCheck', label: 'Random Check' },
            { value: 'stockCheckQr', label: 'Generate QR' },
            { value: 'stockCheckReport', label: 'Stock Check Report' },
            { value: 'stockAudit', label: 'Stock Audit' },
            { value: 'stockAuditDelete', label: 'Stock Audit - Delete' },
            { value: 'stockAuditReset', label: 'Stock Audit - Reset' },
        ],
    },
    {
        key: 'reports',
        label: 'Reports Panel',
        items: [
            { value: 'profitLoss', label: 'Profit/Loss' },
            { value: 'profitLossFlow', label: 'Profit/Loss Flow' },
            { value: 'cashLedger', label: 'Cash Ledger' },
            { value: 'bankLedger', label: 'Bank Ledger' },
            { value: 'supplierDue', label: 'Supplier Due' },
            { value: 'supplierLedger', label: 'Supplier Ledger' },
            { value: 'customerDue', label: 'Customer Due' },
            { value: 'customerLedger', label: 'Customer Ledger' },
            { value: 'productLedger', label: 'Product Ledger' },
            { value: 'stock', label: 'Stock Report' },
            { value: 'expiredWarranty', label: 'Expired Warranty' },
            { value: 'dailyReport', label: 'Daily Report' },
            { value: 'dayBook', label: 'Day Book' },
            { value: 'balanceSheet', label: 'Balance Sheet' },
        ],
    },
];
